language: node_js
node_js:
  - node
  - '8'
script:
  - jest --coverage
after_success:
  - cat ./coverage/lcov.info | codacy-coverage
notifications:
  email:
    on_success: never
    on_failure: change
